# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1

pages:
  stage: deploy
  script:
  - bin/build-pages.sh
  artifacts:
    paths:
    - public
  only:
  - main
  tags:
  - docker
