# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1

pages:
  stage: deploy
  script:
  - mkdir .public
  - php index.php > .public/index.html
  - php buttons.php > .public/buttons.html
  - php content.php > .public/content.html
  - php forms.php > .public/forms.html
  - php grid-system.php > .public/grid-system.html
  - php icons.php > .public/icons.html
  - php lists.php > .public/lists.html
  - php logos.php > .public/logos.html
  - php messages.php > .public/messages.html
  - php navigation.php > .public/navigation.html
  - php pages.php > .public/pages.html
  - php tables.php > .public/tables.html
  - php typography.php > .public/typography.html
  - php widgets.php > .public/widgets.html
  - php videos.php > .public/videos.html
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - docker
