# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1

pages:
  stage: deploy
  script:
  - mkdir .public
  - php index.php > .public/index.html
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - docker

